### ISSUE TITLE
Player with name 'M' not read correctly

### ISSUE THREAD

**Issue by SanderND** [duxbuse/ninthage-data-analytics#66] opened 2021-12-24 14:26 UTC
**Describe the bug**
The lists for The Scottish Championships 2021.docx have a player named 'M' which gives an error.

**To Reproduce**
1. Go to https://discord.com/channels/910334907736272906/915385291429269505/923942759386210306 or read in the attached file.
2. See the value error in the log: "Value Error
Player: "5000 - Warriors of the Dark Gods" not on TK
Extra info: 5000 - Warriors of the Dark Gods
830 - Exalted Herald
830 - Exalted Herald, General
825 - 25x Warriors, Paired Weapons, Great Weapon, Halberd, Greed, Standard Bearer (Zealots' Banner), Musician, Champion
200 - 16x Barbarians, Throwing Weapons, Paired Weapons, Musician
780 - 10x Chosen, Great Weapon, Wrath, Standard Bearer, Musician, Champion
315 - 5x Chosen, Paired Weapons, Gluttony, Musician, Champion
540 - 6x Forsworn, Damnation, Spiked Shield, Musician
200 - Chimera
480 - Hellmaw, Two Ominous Gateways
5000"

This is exactly the list of player named 'M'.

**Expected behavior**
I expect this name to be read in and mapped with player named 'M' on TK
[The Scottish Championships 2021.docx](https://github.com/duxbuse/ninthage-data-analytics/files/7774593/The.Scottish.Championships.2021.docx)
.

**Comment by marcqg** [comment] 2021-12-24 15:06
Hi,

This will be fixed.

**Comment by duxbuse** [comment] 2021-12-26 09:27
this is a duplicate of #58

**Closed by duxbuse** 2021-12-26 09:27 UTC
Labels: bug, Formatter
